myproject/chat/urls.py
from django.urls import path
from . import views

app_name='chat'
urlpatterns=[
  path('<int:pk>/',views.detail,name='detail'),
  path('',views.inbox,name='inbox'),
  path('new/<int:item_pk>/', views.new_chats,name='new'),
   
 
]

myproject/item/urls.py
from django.urls import path
from . import views

app_name = 'item'  # Make sure this matches with your template `{% url 'item:edit' pk=item.pk %}`

urlpatterns = [
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.newitem, name='newitem'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
     path('item/',include('item.urls')),
      path('chat/', include('chat.urls')),
    path('', views.homepage),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
    path('expense_tracker/', include('expense_tracker.urls')),  
  
    path('selling_planner/', include('selling_planner.urls')),
    path('weather/', include('weather.urls')),  
    path('market_prices/', include('market_prices.urls')),
    path('crop_monitoring/', include('crop_monitoring.urls')),
    path('weather/', include('weather.urls')),
    path('calendar/', include('calendar_app.urls')),
    
    

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/posts/urls.py
from django.urls import path
from . import views 

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name = "list"),
    path('new-post/', views.post_new, name = "new-post"),
    path('<slug:slug>', views.post_page, name = "page"),
    path('<slug:slug>/like/', views.toggle_like, name='toggle-like'),
    path('reply/<int:reply_id>/like/', views.like_reply, name='like-reply'),

]

myproject/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/', views.profile_view, name="profile"),
]

myproject/chat/models.py
# chat/models.py
from django.db import models
from django.contrib.auth.models import User
from item.models import Item  


class Chat(models.Model):
    item = models.ForeignKey(Item, related_name='chats', on_delete=models.CASCADE)
    members = models.ManyToManyField(User, related_name='chats')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    delivered = models.BooleanField(default=False)  # Add this field
    
    class Meta:
        ordering = ('-modified_at',)

class ChatMessage(models.Model):
    chat = models.ForeignKey(Chat, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='created_messages', on_delete=models.CASCADE)
    
    class Meta:
        ordering = ('created_at',)

myproject/item/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item-images', blank=True, null=True)  
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class ItemImage(models.Model):
    item = models.ForeignKey(Item, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='item-images/')

    def __str__(self):
        return f"Image for {self.item.name}"

myproject/chat/forms.py
from django import forms
from .models import ChatMessage
class ChatmessagesForm(forms.ModelForm):
  class Meta:
    model=ChatMessage
    fields=('content',)
    widgets={
      'content':forms.Textarea(attrs={
        'class':'w-full py-4 px-6 rounded-xl border'
      })
    }

myproject/item/forms.py
from django import forms
from .models import Item
CLASSES='w-full py-4 px-6 rounded-xl border'
class NewItemForm(forms.ModelForm):
  class Meta:
    model=Item
    fields=('category','name','description','price','image',)
    widgets={
      'category':forms.Select(attrs={
        'class':CLASSES
      }),
      'name':forms.TextInput(attrs={
        'class':CLASSES
      }),
      'description':forms.Textarea(attrs={
        'class':CLASSES
      }),
      'price':forms.TextInput(attrs={
        'class':CLASSES
      }),
      'stock_quantity': forms.NumberInput(attrs={'class': CLASSES}),
      'image':forms.FileInput(attrs={
        'class':CLASSES
      })



    }
class EditItemForm(forms.ModelForm):
  class Meta:
    model=Item
    fields=('name','description','price','image','is_sold')
    widgets = {
      'name':forms.TextInput(attrs={
        'class':CLASSES
      }),
      'description':forms.Textarea(attrs={
        'class':CLASSES
      }),
      'price':forms.TextInput(attrs={
        'class':CLASSES
      }),
      'image':forms.FileInput(attrs={
        'class':CLASSES
      })
    }

myproject/chat/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,get_object_or_404,redirect
from .forms import ChatmessagesForm
from .models import Chat,Item,ChatMessage



@login_required
def new_chats(request,item_pk):
  item= get_object_or_404(Item,pk=item_pk)
  if item.created_by==request.user:
    return redirect('/')
  chats=Chat.objects.filter(item=item).filter(members__in=[request.user.id])

  if chats:
    return redirect('chat:detail',pk=chats.first().id)
   


  if request.method=='POST':
    form=ChatmessagesForm(request.POST)
    if form.is_valid():
      chat=Chat.objects.create(item=item)
      chat.members.add(request.user)
      chat.members.add(item.created_by)
      chat.save()

      chat_message=form.save(commit=False)
      chat_message.chat=chat
      chat_message.created_by=request.user
      chat_message.save()

      return redirect('item:detail',pk=item_pk)
  else:
      form=ChatmessagesForm()
      return render(request,'new.html',{
      'form':form,
    })
@login_required
def inbox(request):
  chats=Chat.objects.filter(members__in=[request.user.id])
  return render(request, 'inbox.html',{
    'chats':chats
  })
@login_required
def detail(request,pk):
  chat=Chat.objects.filter(members__in=[request.user.id]).get(pk=pk)
  if request.method == 'POST':
    form = ChatmessagesForm(request.POST)
    if form.is_valid():
      chat_message=form.save(commit=False)
      chat_message.chat=chat
      chat_message.created_by=request.user
      chat_message.save()
      return redirect('chat:detail',pk=pk)
  else:
    form= ChatmessagesForm()
  return render(request,'chat.html',{
    'chat':chat,
    'form':form,
  })

myproject/item/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from .models import Item,Category
from django.db.models import Q
from .forms import NewItemForm,EditItemForm


def items(request):
 
   items=Item.objects.filter(is_sold=False)
   query=request.GET.get('query','')
   categories=Category.objects.all()
   category_id=request.GET.get('category',0)
   if category_id:
      items=items.filter(category_id=category_id)
   
 
  
   if query:
      items=items.filter(Q(name__icontains=query)|Q(description__icontains=query))
     
      
   return render(request,'items.html',{
      'items':  items,
      'query': query,
      'categories':categories,
      'category_id':int(category_id),

      
      })


def detail(request,pk):
  item=get_object_or_404(Item, pk=pk)
  related_items=Item.objects.filter(category=item.category,is_sold=False).exclude(pk=pk)[0:3]
  return render(request,'detail.html',{
    'item':item,
    'related_items':related_items


  })
@login_required
def newitem(request):
  if request.method=='POST':
    form=NewItemForm(request.POST,request.FILES)
    if form.is_valid():
      item=form.save(commit=False)
      item.created_by=request.user
      item.save()
      return redirect('item:detail',pk=item.id)
  else:
      form=NewItemForm()
  return render(request,'newitem.html',{
    'form': form,
    'title':'New Item',
  })


@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk)

    if item.created_by != request.user:
        return HttpResponseForbidden("You are not allowed to edit this item.")

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=item.pk)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'newitem.html', {
        'form': form,
        'title': 'Edit item',
    })



@login_required
def delete(request,pk):
  item=get_object_or_404(Item,pk=pk,created_by=request.user)
  item.delete()
  
  return redirect('/')

myproject/templates/base.html
<!DOCTYPE html>
<html lang="ne">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <title>{% block title %}{% endblock %}</title>
</head>
<body>

    <nav class="py-5 px-5 flex justify-between items-center border-b" style="background-color: rgb(26, 134, 82);">

    <div class="flex space-x-4 items-center">
      <a href="/" class="px-4 py-2 bg-green-600 text-white rounded-xl hover:bg-green-700 transition font-semibold">
        गृहपृष्ठ फर्किनुहोस्
      </a>
    </div>

    <div class="text-center text-4xl font-bold text-green-300">
      बजारमा स्वागत छ !
    </div>


    <div class="flex space-x-4 items-center">
      <a href="{% url 'chat:inbox' %}" class="bg-white border border-green-600 text-green-700 px-4 py-2 rounded-xl font-semibold hover:bg-green-100 transition">
        Inbox
      </a>
      {% if request.user.is_authenticated and request.user.profile.role == 'farmer' %}
        
       
        <a href="{% url 'item:newitem' %}" class="bg-white border border-green-600 text-green-700 px-4 py-2 rounded-xl font-semibold hover:bg-green-100 transition">
          ➕ सामाग्री थप्नुहोस्
        </a>
        

      {% endif %}
    </div>
  </nav>

  <div class="px-6 py-6">
    {% block content %}
    {% endblock %}
  </div>

</body>
</html>

myproject/templates/detail.html
{% extends 'base.html' %}
{%block title  %} {{item.name}}  {%endblock%}

{%block content %}

<div class="grid grid-cols-5 gap-6">
  <div class="col-span-3">
    <img src="{{ item.image.url }}"  class="rounded-xl">
  </div>

  <div class=" col-span-2 p-6 bg-gray-100 rounded-xl">
    <h1 clss="'mb-6 text-3xl">{{item.name}}</h1>
    <p class=" text-gray-500"><strong>Price:</strong>{{item.price}}</p>
    <p class=" text-gray-500"><strong>Seller:</strong>
      {{item.created_by}}</p>
    {% if item.description%}
    <p class=" text-gray-500"><strong>Description :</strong><br/>  {{item.description}}</p>
    {%endif%}
  
    {% if request.user.profile.role == 'farmer' %}
    <div class="mt-6 p-6 bg-white rounded-xl">
      <p>This is your product (Farmer).</p>
      <a href="{% url 'item:delete' pk=item.pk %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
     
    </div>
    {%endif%}
  {% if request.user.profile.role == 'buyer' %}
  <a href="{% url 'chat:new'  item.id%}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-lime-500  text-white rounded-xl hover:bg-lime-700">Contact Seller</a>
  
    {%endif%}
   
<div class="mt=6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class="mb-12 tect-2xl text-center">
    Suggestions
  </h2>
  <div class="grid grid-cols-3 gap-3">
    {% for item in related_items%}
    <div>
      <a href="{% url 'item:detail' item.id %}">
        <div>
          <img src="{{item.image.url}} " >
        </div>
        <div class="p-6 bg-white ">
          <h2 class="'text-2xl">
            {{item.name}}
          </h2>
          <p class="text-gray-500">Price:{{item.price}}</p>
        </div>
      </a>
    </div>
    {%endfor%}
  </div>

</div>
{%endblock%}

myproject/templates/home.html
{% extends 'layout.html' %} {% block title %}HOME{% endblock %} {% block content%}
<!-- Add Google Fonts -->
<link
  href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap"
  rel="stylesheet"
/>

<style>
  body {
    font-family: "Poppins", sans-serif;
    background: linear-gradient(to bottom, #f0fff4, #e6ffe6);
  }

  .container h2 {
    font-size: 2.5rem;
    font-weight: 800;
    color: #218838;
    text-shadow: 1px 1px 2px #cfcfcf;
  }

  .feature-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 2rem;
    padding: 2rem 3rem;
    place-items: center;
  }

  .feature-item {
    background: rgba(240, 255, 240, 0.85);
    border-radius: 24px;
    padding: 2rem 1.5rem;
    width: 100%;
    max-width: 320px;
    height: 260px;
    text-align: center;
    text-decoration: none;
    color: #2d3436;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    box-shadow: 0 4px 16px rgba(0, 100, 0, 0.15);
    backdrop-filter: blur(4px);
    transition: all 0.3s ease-in-out;
  }

  .feature-item:hover {
    transform: translateY(-6px) scale(1.02);
    background: rgba(204, 255, 204, 0.9);
    box-shadow: 0 8px 20px rgba(0, 128, 0, 0.3);
  }

  .feature-item svg {
    margin-bottom: 1rem;
    width: 60px;
    height: 60px;
    color: #28a745;
    transition: transform 0.2s ease;
    object-fit: contain;
  }

  .feature-item:hover svg {
    transform: scale(1.1);
  }

  .feature-item strong {
    font-size: 1.2rem;
    font-weight: 700;
    color: #14532d;
  }

  .feature-item small {
    color: #555;
    font-size: 0.95rem;
  }

  .feature-item div {
    font-size: 16px;
    line-height: 1.2;
  }

  @media (max-width: 768px) {
    .container h2 {
      font-size: 2rem;
    }

    .feature-item {
      height: auto;
      padding: 1.5rem;
    }
  }
</style>

<div class="container text-center my-4">
  <h2>समृद्ध किसान</h2>
</div>

<div class="feature-grid">
  <a href="/weather/" class="feature-item">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="currentColor"
    >
      <path
        fill-rule="evenodd"
        d="M4.5 9.75a6 6 0 0 1 11.573-2.226 3.75 3.75 0 0 1 4.133 4.303A4.5 4.5 0 0 1 18 20.25H6.75a5.25 5.25 0 0 1-2.23-10.004 6.072 6.072 0 0 1-.02-.496Z"
        clip-rule="evenodd"
      />
    </svg>
    <div>
      <strong>Weather Information</strong><br /><small>मौसम जानकारी</small>
    </div>
  </a>

  <a href="/expense_tracker/" class="feature-item">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M15 8.25H9m6 3H9m3 6-3-3h1.5a3 3 0 1 0 0-6M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
      />
    </svg>
    <div><strong>Income & Expense</strong><br /><small>कमाई र खर्च</small></div>
  </a>

  <a href="/market_prices/" class="feature-item">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M3.75 3v11.25A2.25 2.25 0 0 0 6 16.5h2.25M3.75 3h-1.5m1.5 0h16.5m0 0h1.5m-1.5 0v11.25A2.25 2.25 0 0 1 18 16.5h-2.25m-7.5 0h7.5m-7.5 0-1 3m8.5-3 1 3m0 0 .5 1.5m-.5-1.5h-9.5m0 0-.5 1.5m.75-9 3-3 2.148 2.148A12.061 12.061 0 0 1 16.5 7.605"
      />
    </svg>
    <div><strong>Market Prices</strong><br /><small>बजार मूल्य</small></div>
  </a>


  <a href="/item/" class="feature-item">
    <svg
      fill="#28a745"
      viewBox="0 0 1000 1000"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M891 308H340q-6 0-10.5-4t-5.5-10l-32-164q-2-14-12-22.5T256 99H110q-15 0-25.5 10.5T74 135v5q0 15 10.5 26t25.5 11h102q4 0 7 2.5t4 6.5l102 544q3 19 20 28 8 5 18 5h17q-22 25-21 58.5t25 56.5 57.5 23 58-23 25.5-56.5-22-58.5h186q-23 25-21.5 58.5T693 878t57.5 23 57.5-23 25-56.5-21-58.5h17q15 0 25.5-10.5T865 727v-8q0-15-11-25.5T828 683H409q-6 0-10.5-4t-5.5-9l-10-54q-1-8 4-14t12-5h460q13 0 22.5-8t11.5-21l33-219q3-16-7.5-28.5T891 308z"
      />

  <a href="/item/" class="feature-item">
    <svg fill="#28a745" viewBox="0 0 1000 1000" xmlns="http://www.w3.org/2000/svg">
      <path d="M891 308H340q-6 0-10.5-4t-5.5-10l-32-164q-2-14-12-22.5T256 99H110q-15 0-25.5 10.5T74 135v5q0 15 10.5 26t25.5 11h102q4 0 7 2.5t4 6.5l102 544q3 19 20 28 8 5 18 5h17q-22 25-21 58.5t25 56.5 57.5 23 58-23 25.5-56.5-22-58.5h186q-23 25-21.5 58.5T693 878t57.5 23 57.5-23 25-56.5-21-58.5h17q15 0 25.5-10.5T865 727v-8q0-15-11-25.5T828 683H409q-6 0-10.5-4t-5.5-9l-10-54q-1-8 4-14t12-5h460q13 0 22.5-8t11.5-21l33-219q3-16-7.5-28.5T891 308z" />
>>>>>>> e2218fe3b8199a0c3e8616f7ff97e2eae641fc85
    </svg>
    <div><strong>Marketplace</strong><br /><small>बजार</small></div>
  </a>

  <a href="{% url 'posts:list' %}" class="feature-item">
    <svg fill="#28a745" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
      <path
        d="M8.4,16.8A3,3,0,0,0,9,15a3,3,0,0,0-6,0,3,3,0,0,0,.6,1.8A4,4,0,0,0,2,20v1a1,1,0,0,0,1,1H9a1,1,0,0,0,1-1V20A4,4,0,0,0,8.4,16.8Z"
      />
      <path
        d="M22,7v3a2,2,0,0,1-2,2H16.24l-3.79,1.89A1,1,0,0,1,12,14a1,1,0,0,1-.53-.15A1,1,0,0,1,11,13V11.73A2,2,0,0,1,10,10V7a2,2,0,0,1,2-2h8A2,2,0,0,1,22,7Z"
      />
    </svg>
    <div><strong>Discussion Forum</strong><br /><small>छलफल</small></div>
  </a>

  <a href="/calendar/" class="feature-item">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="currentColor"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5"
      />
    </svg>
    <div>
      <strong>Crop Selling Planner</strong><br /><small>बिक्री योजना</small>
    </div>
  </a>

  {% comment %}
  <a href="/crop_monitoring/" class="feature-item" style="grid-column: 2 / 3">
    <svg fill="#28a745" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
      <path
        d="M5.859,8.341a5.876,5.876,0,0,0,5.283.117A9,9,0,0,0,11,10v2H6a1,1,0,0,0-1,1v3a1,1,0,0,0,1,1H7v5a1,1,0,0,0,1,1h8a1,1,0,0,0,1-1V17h1a1,1,0,0,0,1-1V13a1,1,0,0,0-1-1H13V10a7.008,7.008,0,0,1,7-7,1,1,0,0,0,0-2,8.993,8.993,0,0,0-7.642,4.27C11.415,3.55,9.155,1,4,1A1,1,0,0,0,3,2C3,2.187,3.033,6.594,5.859,8.341Z"
      />
    </svg>
    <div>
      <strong>Crop Monitoring</strong><br /><small>बाली मूल्याङ्कन</small>
    </div>
  </a>
  {% endcomment %}
</div>
{% endblock %}

myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="ne">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}समृद्ध किसान{% endblock %}</title>
    <script src="{% static 'static/js/main.js' %}" defer></script>
    {% block styles %}{% endblock %}
    <link rel="stylesheet" href="{% static 'static/css/style.css' %}" />
  </head>
  <body>
    <nav
      class="flex flex-wrap items-center justify-between p-4 bg-green-500 text-white shadow-md text-sm"
    >
      <div class="flex items-center gap-3">
        <a
          href="/"
          class="flex flex-col items-center hover:text-lime-100"
          title="गृहपृष्ठ"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            width="28"
            height="28"
          >
            <path
              d="M11.47 3.841a.75.75 0 0 1 1.06 0l8.69 8.69a.75.75 0 1 0 1.06-1.061l-8.689-8.69a2.25 2.25 0 0 0-3.182 0l-8.69 8.69a.75.75 0 1 0 1.061 1.06l8.69-8.689Z"
            />
            <path
              d="m12 5.432 8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 0 1-.75-.75v-4.5a.75.75 0 0 0-.75-.75h-3a.75.75 0 0 0-.75.75V21a.75.75 0 0 1-.75.75H5.625a1.875 1.875 0 0 1-1.875-1.875v-6.198a2.29 2.29 0 0 0 .091-.086L12 5.432Z"
            />
          </svg>

          <span class="text-xs mt-1">गृहपृष्ठ</span>
        </a>
      </div>

      <div class="flex items-center gap-6">
        {% if user.is_authenticated %}
        <form
          action="{% url 'users:logout' %}"
          method="post"
          class="flex flex-col items-center"
        >
          {% csrf_token %}
          <button title="लग आउट" class="logout-button">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="currentColor"
              width="28"
              height="28"
            >
              <path
                fill-rule="evenodd"
                d="M7.5 3.75A1.5 1.5 0 0 0 6 5.25v13.5a1.5 1.5 0 0 0 1.5 1.5h6a1.5 1.5 0 0 0 1.5-1.5V15a.75.75 0 0 1 1.5 0v3.75a3 3 0 0 1-3 3h-6a3 3 0 0 1-3-3V5.25a3 3 0 0 1 3-3h6a3 3 0 0 1 3 3V9A.75.75 0 0 1 15 9V5.25a1.5 1.5 0 0 0-1.5-1.5h-6Zm5.03 4.72a.75.75 0 0 1 0 1.06l-1.72 1.72h10.94a.75.75 0 0 1 0 1.5H10.81l1.72 1.72a.75.75 0 1 1-1.06 1.06l-3-3a.75.75 0 0 1 0-1.06l3-3a.75.75 0 0 1 1.06 0Z"
                clip-rule="evenodd"
              />
            </svg>
            {% comment %} <span class="text-[8px] mt-1">logout</span> {% endcomment %}
          </button>
        </form>
        {% else %}
        <a
          href="{% url 'users:register' %}"
          title="दर्ता गर्नुहोस्"
          class="hover:text-lime-100 flex flex-col items-center"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            width="28"
            height="28"
          >
            <path
              d="M5.25 6.375a4.125 4.125 0 1 1 8.25 0 4.125 4.125 0 0 1-8.25 0ZM2.25 19.125a7.125 7.125 0 0 1 14.25 0v.003l-.001.119a.75.75 0 0 1-.363.63 13.067 13.067 0 0 1-6.761 1.873c-2.472 0-4.786-.684-6.76-1.873a.75.75 0 0 1-.364-.63l-.001-.122ZM18.75 7.5a.75.75 0 0 0-1.5 0v2.25H15a.75.75 0 0 0 0 1.5h2.25v2.25a.75.75 0 0 0 1.5 0v-2.25H21a.75.75 0 0 0 0-1.5h-2.25V7.5Z"
            />
          </svg>

          <span class="text-xs mt-1">दर्ता</span>
        </a>

        <a
          href="{% url 'users:login' %}"
          title="लगइन"
          class="hover:text-lime-100 flex flex-col items-center"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            width="28"
            height="28"
          >
            <path
              fill-rule="evenodd"
              d="M18.685 19.097A9.723 9.723 0 0 0 21.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 0 0 3.065 7.097A9.716 9.716 0 0 0 12 21.75a9.716 9.716 0 0 0 6.685-2.653Zm-12.54-1.285A7.486 7.486 0 0 1 12 15a7.486 7.486 0 0 1 5.855 2.812A8.224 8.224 0 0 1 12 20.25a8.224 8.224 0 0 1-5.855-2.438ZM15.75 9a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z"
              clip-rule="evenodd"
            />
          </svg>

          <span class="text-xs mt-1">लगइन</span>
        </a>
        {% endif %}
      </div>
    </nav>

    <main class="mt-4 px-4">{% block content %} {% endblock %}</main>
  </body>
</html>